import './globals.css'
import { Inter } from 'next/font/google'
import StyledComponentsRegistry from "./registry";
import Navbar from '@/components/Navbar/Navbar';
import Footer from '@/components/Footer';
import { Account } from '@/context/Account'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'UniRent',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <Account>
            <Navbar />
            {children}
            <Footer />
          </Account>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
